### ISSUE TITLE
link mySql 

### ISSUE THREAD

**Issue by clement360** [docker-library/drupal#1]
Hello, this is how I started my drupal instance

1. create the mysql container <code>docker run --name some-mysql -e MYSQL_ROOT_PASSWORD=drupal -d mysql</code>

2. create and link drupal: <code>docker run --name some-drupal --link some-mysql:mysql -p 8080:80 -d drupal</code>

![image](https://cloud.githubusercontent.com/assets/2770596/7498831/ae1e86d6-f3f1-11e4-9c69-270b4ba1f82b.png)

I visit my ip:8080 and start the installation and none of my mysql creds are linked. 
![image](https://cloud.githubusercontent.com/assets/2770596/7498808/828d9106-f3f1-11e4-98ef-61cd86b99478.png)

Shouldn't I not need to go through the db setting if I have a mySql linked?

**Comment by tianon** [comment]
I actually played quite a bit with pre-seeding these settings in the case of a linked container, and couldn't get Drupal to pick up the settings properly.  If you look at the documentation on https://registry.hub.docker.com/_/drupal/, it explains that you have to enter appropriate values for these options during the setup wizard, and provides the options you'll need depending on the database you choose (screenshot of the relevant portion below).

![image](https://cloud.githubusercontent.com/assets/161631/7499435/dedac33c-f3e4-11e4-9213-da4ebfc85f07.png)

**Comment by clement360** [comment]
ok thanks for the quick reply!
I can do that with -e flags. but what if I wanted to change the db host to use a database running on AWS or IBM Bluemix. is there an environment variable in drupal like MYSQL_HOST ?

**Comment by tianon** [comment]
Naw, you'd just set that host directly in the "Database host" portion of
the setup (instead of setting it to just "mysql").
