### ISSUE TITLE
Configuring the drupal docker container to use an AWS RDS DB

### ISSUE THREAD

**Issue by hapnermw** [docker-library/drupal#101]
The current drupal container doc describes the use of the deprecated docker link facility to 'link' a drupal container to a local db container. 

First, this is bad - you need stop using link.

Second, using the drupal container with an external DB seems like a pretty common case - much more common than running the db as a local container. Why is there no doc for this case?

I need to connect a drupal container to an RDS DB instance. I'm hoping that by creating a settings.php with the correct config and building a new drupal container with this settings.php in /var/www/html/ this will config drupal to use my RDS DB.

How do I verify if this is working?  Is there some other solution to this issue?

**Comment by yosifkit** [comment]
Links are used in the description to make it easier to describe. We don't have to explain how to create (and clean up) a network when a user only wants to quickly test the image.  If they want something more complicated, the `stack.yaml` is further down in the description.

As for settings, we don't have an entrypoint that reads environment variables, it is all up to you to run through the initial setup wizard. It looks like all of the database settings are saved there: https://www.drupal.org/docs/7/install/step-3-create-settingsphp-and-the-files-directory, so as long as you set the correct permissions and setup anything else that the install script does it should be fine.

You could test it by creating a `settings.php` that will connect to a local sql in a container and build an image for that.

**Comment by hapnermw** [comment]
Hi yosifkit,

A container image should be ready to use for production. The Drupal
container image is not and the docs do not provide the info needed to use
it in production.

Someone on the project needs to understand what it means to provide a
production ready container image. The docker stack docs are not useful -
few production deployments of Drupal will use a docker stack.

To clarify this point, let me describe how I'm deploying a Drupal Server.

I'm deploying an NginX and Drupal server on AWS with mulltiple EC2 CoreOS
instances and an RDS Aurora MySQL DB.

Each instance contains a NginX and Drupal systemd service - each service
runs a Docker container. Each instance contains a drupal/var/www/html
directory mounted to an EFS file system containing the content of
/var/www/html. This content is a copy of /var/www/html from the Drupal
container image with the sites/settings.php database array set to reference
the RDS DB. This drupal directory is passed as a docker volume to both
NginX and Drupal as /var/www/html. NginX is configured using its Drupal
recipe[1] and its PHP FastCGI Example[2]. NginX is configured to access
Drupal's fpm on port 9000.

You need to provide some practical production deployment advice such as
this for the community using the Drupal container.

Anyone seeing docs describing the use of a docker link to configure a
database for Drupal knows immediately that the docs were written by someone
who doesn't understand what it means to deploy containers in production
much less for a test config (which also should not use link).

The same goes for the docker stack docs.

If someone there would like to dig into this further, I would be happy to
discuss it with them.

[1] https://www.nginx.com/resources/wiki/start/topics/recipes/drupal/

[2] https://www.nginx.com/resources/wiki/start/topics/examples/phpfcgi/

-- Mark

**Comment by mstenta** [comment]
@hapnermw Good information - you should put together a pull request to the docs repo: https://github.com/docker-library/docs/tree/master/drupal

**Comment by hapnermw** [comment]
Thanks, since I'm just the guy provisioning the Drupal server, once the
users of it have verified it works well I'll do that.

Since container size is important for scale out, it would be nice if Drupal
could provide an Alpine rc-fpm image.

**Comment by mstenta** [comment]
I think there is an Alpine fpm image already?

https://github.com/docker-library/drupal/blob/30b3f40a64a8f128f0bff32f7e76eb9bc041cba5/7/fpm-alpine/Dockerfile

https://github.com/docker-library/drupal/blob/3bb4c69b95ae8240ab636a810aa78c64ae6e43c5/8.4/fpm-alpine/Dockerfile

**Comment by hapnermw** [comment]
Yes, I see it now. For some reason I had seen only the 7 one. Sorry ...

**Comment by tianon** [comment]
We'll look forward to your improved documentation PR. :heart:

(Closing, since there doesn't appear to be anything actionable left here.)
