### ISSUE TITLE
PHP Startup: Unable to load dynamic library 'gd.so'

### ISSUE THREAD

**Issue by hapnermw** [docker-library/drupal#102]
I'm using the current rc-fpm container image. It appears that for some reason php-fpm can't find gd.so in the container even though it is in the container.

When I run the container with the default Cmd (php-fpm) it logs this warning:

[14-Feb-2018 21:55:01] NOTICE: PHP message: PHP Warning:  PHP Startup: Unable to load dynamic library 'gd.so' (tried: /usr/local/lib/php/extensions/no-debug-non-zts-20170718/gd.so (libpng16.so.16: cannot open shared object file: No such file or directory), /usr/local/lib/php/extensions/no-debug-non-zts-20170718/gd.so.so (/usr/local/lib/php/extensions/no-debug-non-zts-20170718/gd.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
Usage: php [-n] [-e] [-h] [-i] [-m] [-v] [-t] [-p <prefix>] [-g <pid>] [-c <file>] [-d foo[=bar]] [-y <file>] [-D] [-F [-O]]

In fact, gd.so is exactly where it should be in the container:

core@ip-10-0-6-213 ~ $ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
deb8ab170e4c        nginx:alpine        "nginx -c /etc/nginx/"   2 days ago          Up 2 days                               lb-cntnr
b629fbab59e7        drupal:rc-fpm       "docker-php-entrypoin"   2 days ago          Up 2 days                               drupal-cntr
core@ip-10-0-6-213 ~ $ docker exec b629fbab59e7 ls /usr/local/lib/php/extensions/no-debug-non-zts-20170718/
gd.so
mbstring.so
opcache.a
opcache.so
pdo.so
pdo_mysql.so
pdo_pgsql.so
zip.so

**Comment by yosifkit** [comment]
Hm, it looks like this should've been broken on all versions, but the `libpng12-0` package in jessie (php 7.0 and 7.1) sticks around, while the `libpng16-16` package in stretch does not.  I'll make a PR to fix the extension installation steps.
