### ISSUE TITLE
Add Drupal 8.5.0

### ISSUE THREAD

**Issue by juliencarnot** [docker-library/drupal#105]
https://www.drupal.org/project/drupal/releases/8.5.0 is out...

**Comment by tianon** [comment]
https://github.com/docker-library/drupal/pull/104; https://github.com/docker-library/drupal/blob/master/README.md

> See a change merged here that doesn't show up on the Docker Hub yet? Check [the "library/drupal" manifest file in the docker-library/official-images repo](https://github.com/docker-library/official-images/blob/master/library/drupal), especially [PRs with the "library/drupal" label on that repo](https://github.com/docker-library/official-images/labels/library%2Fdrupal). For more information about the official images process, see the [docker-library/official-images readme](https://github.com/docker-library/official-images/blob/master/README.md).

There'll be a PR today.
