### ISSUE TITLE
Environment variables to automate profile, language and db configurations for drupal installation

### ISSUE THREAD

**Issue by anu17** [docker-library/drupal#106]
Can we create an entrypoint.sh file with the environment variables to automate profile, language and db configurations for drupal installation?

**Comment by anu17** [comment]
similar to what we have in https://github.com/samos123/docker-drupal/blob/master/entrypoint.sh

**Comment by tianon** [comment]
Don't those settings live inside the database that Drupal is connected to? (so for us to set them would require not only an initialized database, but also something like `drush` to change them?)

**Comment by wglambert** [comment]
Closing since this isn't something we're going to implement
