### ISSUE TITLE
what's the difference between drupal:8.5-fpm and 8.5-apache?

### ISSUE THREAD

**Issue by Jahng** [docker-library/drupal#107]
what's the difference between 8.5-fpm image and 8.5-apache? If there are only the php-fpm configurations for drupal8 in 8.5-fpm image?

**Comment by yosifkit** [comment]
The `apache` variants use Apache httpd to run the php code via `mod_php` and serves up web pages directly. The `fpm` variants are just php using [php-fpm](https://php-fpm.org/) and are just exposing the [fastcgi](https://en.wikipedia.org/wiki/FastCGI) protocol, so it requires a web server (like nginx or httpd) in front to serve up http to browsers.

**Comment by Jahng** [comment]
If so, I do not think it is necessary to download the drupal source code in  8.5-fpm image, since I have no idea how to share the source code between nginx container and drupal:8.5-fpm container without volunm

**Comment by tianon** [comment]
A volume is definitely the _easiest_ way to do so.

**Comment by Jahng** [comment]
yes, tianon, I agree with you, and for this reason, I don't think the drupal source code should be downloaded in drupal:8.5-fpm, this will make the image more heavier.

**Comment by tianon** [comment]
If we don't include the source, then we're saying to users that they need to go find and download the source of Drupal themselves, in which case we're no longer providing much value over simply using the `php:fpm` image directly.
