### ISSUE TITLE
8.3/8.4 Critical Security Update

### ISSUE THREAD

**Issue by bushong1** [docker-library/drupal#108]
Will these critical updates be pushed to docker hub for 8.3.9 and 8.4.6?  https://www.drupal.org/sa-core-2018-002

The 8.3/8.4 docker libraries were EOL'd under the assumption that there would be no more updates, but here we are.  Any information you provide would be very helpful.  Thank!

**Comment by yosifkit** [comment]
Done: https://github.com/docker-library/official-images/pull/4186
