### ISSUE TITLE
Changes from #113 not in Docker Hub

### ISSUE THREAD

**Issue by bushong1** [docker-library/drupal#114]
Still waiting for the changes from #113 to make it into docker hub.  Sorry to be persistent, but this is causing us some major strife with the 8.3.9 build being broken :-)

How long does it roughly take to get updates into Docker Hub?

**Comment by yosifkit** [comment]
I just merged https://github.com/docker-library/official-images/pull/4191 and they are currently building.

**Comment by bushong1** [comment]
Awesome, i'll Close this.
