### ISSUE TITLE
Getting error when running on AWS EC2.

### ISSUE THREAD

**Issue by rishavpathania1995** [docker-library/drupal#124]
when i run the following 
`docker run --name some-drupal -p 8080:80 -d drupal`
nothing is showing up on local  host .
and also check the logs 
`AH00558: apache2: Could not reliably determine the server's fully qualified doma                                                                                        in name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress t                                                                                        his message
AH00558: apache2: Could not reliably determine the server's fully qualified doma                                                                                        in name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress t                                                                                        his message
[Thu Jul 12 18:48:20.881952 2018] [mpm_prefork:notice] [pid 1] AH00163: Apache/2                                                                                        .4.25 (Debian) PHP/7.2.7 configured -- resuming normal operations
[Thu Jul 12 18:48:20.882038 2018] [core:notice] [pid 1] AH00094: Command line: '                                                                                        apache2 -D FOREGROUND'
`

**Comment by mstenta** [comment]
It's working as expected. That's a warning, not an error. Apache is running.

If you Google that warning, this is the first result that comes up: https://askubuntu.com/questions/256013/apache-error-could-not-reliably-determine-the-servers-fully-qualified-domain-n

**Comment by wglambert** [comment]
```console
$ docker run --name some-drupal -p 8080:80 -d drupal
de27e1787c0f61f057d478c817d1fbd0cd4acf4e98b14604221bb14cba8804bb
$ curl localhost:8080
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="refresh" content="0;url=/core/install.php" />

        <title>Redirecting to /core/install.php</title>
    </head>
    <body>
        Redirecting to <a href="/core/install.php">/core/install.php</a>.
    </body>
</html>
```

Could you show the output of running these commands
