### ISSUE TITLE
Drupal in docker container - getpwuid error in log file

### ISSUE THREAD

**Issue by derekoharrow** [docker-library/drupal#125]
I'm running Drupal in a docker container. The web-site is up and running fine, but it seems to take quite a while for the container to get started and I get the following message multiple times in the log file...

`[Mon Jul 16 13:14:11.722725 2018] [unixd:alert] [pid 27] AH02155: getpwuid: couldn't determine user name from uid 1000, you probably need to modify the User directive`

My docker-compose looks like this:

`  drupal:

    container_name: drupal

    image: drupal:8-apache

    depends_on:

      - mariadb

    ports:

      - 9118:80

    volumes:

      - /data/appdata/www/www/html/domainname.com/public_html/modules:/var/www/html/modules

      - /data/appdata/www/www/html/domainname.com/public_html/profiles:/var/www/html/profiles

      - /data/appdata/www/www/html/domainname.com/public_html/themes:/var/www/html/themes

      - /data/appdata/www/www/html/domainname.com/public_html/sites:/var/www/html/sites

    tmpfs:

      - /tmp

    environment:

      - PUID=${PUID}

      - PGID=${PGID}

      - TZ=${TZ}

      - APACHE_RUN_USER=#1000

      - APACHE_RUN_GROUP=#999

    restart: always
`

From what I've read, it sounds like getpwuid is trying to read the passwd file and get the user associated with the UID. As it's running in a container, I'm guessing the user doesn't exist in the passwd file, hence the issue.

Thoughts?

**Comment by tianon** [comment]
It sounds like you've diagnosed the situation accurately -- you'll ether want/need to populate `/etc/passwd` with a user for UID 1000 or stop setting `APACHE_RUN_USER` if this is causing issues (this is an upstream bug -- there's not really anything we can do in the image to fix it that I'm aware of).

You _might_ be able to simply bind-mount your host's `/etc/passwd` file (I'd recommend doing so read-only), but only if it's got a user with ID 1000.
