### ISSUE TITLE
How to upgrade to php 7.2.5

### ISSUE THREAD

**Issue by tkserver** [docker-library/drupal#127]
Currently running 8.5.1-apache which is running php 7.2.4.  7.2.4 has some vulnerabilities and I'd like to upgrade my container to 7.2.5.  How can that be done?

**Comment by tianon** [comment]
Given that 8.5.1 is an older release, it will not be rebuilt.  If you absolutely require 8.5.1, you're going to have to build your own image (which shouldn't be too hard to do based on the `Dockerfile`s from this repository).

If you switch to just `drupal:8.5-apache`, you'll be on PHP 7.2.8 (which is the latest release) and Drupal 8.5.5:

```console
$ docker pull drupal:8.5-apache
8.5-apache: Pulling from library/drupal
Digest: sha256:970b09f0c2a331145c3ead82234bf2a570400f2b2769a07b4c156cbdbf379c5b
Status: Image is up to date for drupal:8.5-apache

$ docker run --rm drupal:8.5-apache php --version
PHP 7.2.8 (cli) (built: Jul 21 2018 07:52:06) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.8, Copyright (c) 1999-2018, by Zend Technologies
```

**Comment by tkserver** [comment]
Perfect! Don't need to stay on 8.5.1. There are some security vulnerabilities on < 8.5.5
