### ISSUE TITLE
drupal:8-fpm does not create Unix socket file

### ISSUE THREAD

**Issue by kenneho** [docker-library/drupal#130]
Hi.

I'm using drupal:8-fpm as a basis for my Drupal installation. When I override the `/usr/local/etc/php-fpm.d/www.conf` file to include `listen = 127.0.0.1:9000`, things work fine, but when I change to `listen = /run/docker.sock`, the `/run/docker.sock` file is not created and thus php-fpm is not accepting any requests. 

Is this a bug in how the image is set up, or isn't this the correct way of switching from TCP socket to Unix socket?

**Comment by wglambert** [comment]
You have to map the `docker.sock`

The entry in your compose file
```.yml
volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

**Comment by kenneho** [comment]
Thanks for the reply. 

I was under the impression that php-fpm itself would create that socket file. Anyway, I tried to create it myself, as you suggested, like this:

```
volumes:
      - ~/sock/docker.sock:/var/run/docker.sock
```

Note that to ensure that the user running php-fpm (www-data) would have r/w access to the file, I used ~/sock/docker.sock instead (which is owned by a host user with the same UID as www-data). 

After configuring Nginx to use the same socket file for communicating with php-fpm, I started the container. Nginx have acess to the same file, but still logs these errors: 

> connect() to unix:/var/run/docker.sock failed (111: Connection refused) while connecting to upstream, client: 1.2.3.4, server: intranet, request: "GET /", upstream: "fastcgi://unix:/var/run/docker.sock:"

As I believe the Nginx container is configured correctly, I thought I'd look and see if I can verify that php-fpm indeed works as expected. I came across [this StackOverflow post](https://stackoverflow.com/questions/14915147/php-fpm-check-if-running) that suggested I could use socat to check if php-fpm is actually listening on the specified unix socket. So I ran this command: 

```
www-data@78ac42ece484:/app$ echo /dev/null | socat UNIX:/var/run/docker.sock -
2018/08/08 07:05:59 socat[26] E connect(5, AF=1 "/var/run/docker.sock", 22): Connection refused
```

So it looks like php-fpm doesn't listen to the socket. The php-fpm config file looks like this:

```
www-data@78ac42ece484:/app$ egrep -v ";|^$" /usr/local/etc/php-fpm.d/www.conf
[www]
user = www-data
group = www-data
listen = /var/run/docker.sock
listen.mode = 0666
pm = dynamic
pm.max_children = 5
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3
```

Any ideas on how to proceed troubleshooting this issue?

**Comment by tianon** [comment]
You need to make sure that your `listen` instruction is the last one that FPM reads (which is why `zz-docker.conf` includes our `listen = 9000` line to overwrite the same value in `www.conf`).

I had success with creating `zzzzzz-me.conf` (to make sure it's definitely loaded after `zz-docker.conf`, which you could also just as easily either remove or replace as long as you keep the `daemonize = no` from it) and adding `listen = /run/fpm.sock` which successfully created `/run/fpm.sock`.

**Comment by kenneho** [comment]
Thanks, your how-to worked!

**Comment by zura101** [comment]
> You need to make sure that your `listen` instruction is the last one that FPM reads (which is why `zz-docker.conf` includes our `listen = 9000` line to overwrite the same value in `www.conf`).
> 
> I had success with creating `zzzzzz-me.conf` (to make sure it's definitely loaded after `zz-docker.conf`, which you could also just as easily either remove or replace as long as you keep the `daemonize = no` from it) and adding `listen = /run/fpm.sock` which successfully created `/run/fpm.sock`.

Thank you, I spent hours to find out what was the problem
