### ISSUE TITLE
Add  bcmath PHP extension

### ISSUE THREAD

**Issue by imikiani** [docker-library/drupal#133]
Hi,
when we want to install Drupal commerce 2, the following message appears:

> Commerce requires the bcmath PHP extension.

**Comment by mstenta** [comment]
I think this line by itself would work in a custom Dockerfile that extends the Drupal one:

`RUN docker-php-ext-install bcmath`

**Comment by wglambert** [comment]
https://github.com/docker-library/docs/tree/master/drupal#adding-additional-libraries--extensions
>If you need additional PHP extensions, you'll need to create your own image `FROM` this one. The [documentation of the `php` image](https://github.com/docker-library/docs/blob/master/php/README.md#how-to-install-more-php-extensions) explains how to compile additional extensions. Additionally, the [`drupal:7` Dockerfile](https://github.com/docker-library/drupal/blob/bee08efba505b740a14d68254d6e51af7ab2f3ea/7/Dockerfile#L6-9) has an example of doing this.
