### ISSUE TITLE
Set max file upload size

### ISSUE THREAD

**Issue by BoyCook** [docker-library/drupal#135]
How do I set the max upload size? The default seems to be 2MB. This would be set in php.ini but I don't see a way to do this: https://www.drupal.org/docs/7/managing-site-performance-and-scalability/increase-upload-size-in-your-phpini

**Comment by wglambert** [comment]
Drupal is `FROM PHP` so the docs on configuring PHP are relevant https://github.com/docker-library/docs/tree/master/php#configuration
