### ISSUE TITLE
Use PHP 7.1 for Drupal 7

### ISSUE THREAD

**Issue by alberto56** [docker-library/drupal#136]
The drupal 7 image currently uses php 7.0; however [Drupal 7 now supports 7.1](https://www.drupal.org/docs/7/system-requirements/drupal-7-php-requirements); can we use version 7.1 of PHP as a base image?

**Comment by yosifkit** [comment]
Should we just wait for `7.61` and go directly to PHP 7.2? (As far as I can tell that should be the first Wednesday of the month, ie should be today: https://groups.drupal.org/node/534483)

> (4) The coming 7.61 release will support 7.2 - see [relevant core issue](https://www.drupal.org/project/drupal/issues/2947772).
>
> \- https://www.drupal.org/docs/7/system-requirements/drupal-7-php-requirements#php_required

**Comment by mirabuck** [comment]
I suspect that a direct jump to 7.2 will yield at least a few problems with contrib modules not keeping pace,  Maybe 7.1 makes more sense to start?

**Comment by mirabuck** [comment]
For context, 7.0 is EOL December 5th, 2018.
