### ISSUE TITLE
Docker Hub not representing security updates as Docker images

### ISSUE THREAD

**Issue by codycraven** [docker-library/drupal#142]
Updates for Drupal's security releases yesterday, including 8.5.9 and 8.5.10 are not published to https://hub.docker.com/_/drupal

I found that master in this repository did contain the updates so I needed to build my own image as a fill-gap from the master Dockerfile needed until the issue is resolved.

**Comment by wglambert** [comment]
https://github.com/docker-library/mysql#see-a-change-merged-here-that-doesnt-show-up-on-docker-hub-yet

It's being pushed now Dockerhub https://github.com/docker-library/official-images/pull/5306

**Comment by yosifkit** [comment]
Should be appearing shortly once the build servers get it done.
