### ISSUE TITLE
Database host ENV variable

### ISSUE THREAD

**Issue by CloudGrimm** [docker-library/drupal#146]
I am trying to hint my database host in the yaml configurations like how I also did that for 

MYSQL_DATABASE, what is the right way to hint that for this image?

**Comment by tianon** [comment]
This image doesn't contain any entrypoint for configuring Drupal via environment variables, so unfortunately any support for this would have to come from Drupal itself.

I believe https://www.drupal.org/project/drupal/issues/2879846 is the upstream issue where this functionality is being discussed.
