### ISSUE TITLE
No 7.67 tag?

### ISSUE THREAD

**Issue by FraserThompson** [docker-library/drupal#151]
It looks like the image has been updated to 7.67 but the latest tag in Docker hub is still 7.66 according to: https://hub.docker.com/_/drupal?tab=tags

**Comment by tianon** [comment]
See https://github.com/docker-library/drupal#see-a-change-merged-here-that-doesnt-show-up-on-docker-hub-yet and https://github.com/docker-library/official-images/pull/5892. :+1:
