### ISSUE TITLE
Update base image to php:7.3-apache (buster)

### ISSUE THREAD

**Issue by philltran** [docker-library/drupal#157]
It looks like the [issue 865]( https://github.com/docker-library/php/issues/865) referenced in the TODO has been closed, so we can update base image to use buster. The dockerfile built fine for me using `php:7.3-apache`

**Comment by yosifkit** [comment]
Closing old issue.

There are Drupal images based on PHP 7.4 and 8.0 (if supported) with the choice of Debian Buster, Debian Bullseye, or Alpine 3.14 or 3.15.
