### ISSUE TITLE
Add Drush

### ISSUE THREAD

**Issue by iBobik** [docker-library/drupal#16]
Are you open to include Drush into this image? If yes, I will prepare PR, if not I will do it in my derivated image.

**Comment by skyred** [comment]
As the doc says https://github.com/docker-library/docs/tree/master/drupal#adding-additional-libraries--extensions

This image is trying to maintain the very minimal. But, you can include Drush in your image based on this, all you need to do is below:

````
FROM drupal:8.0

# install Composer globally
RUN curl -sS https://getcomposer.org/installer | php \
  && mv composer.phar /usr/local/bin/composer

# install Drush 8.x
RUN composer global require drush/drush:dev-master \
  && echo "export PATH=\"$HOME/.composer/vendor/bin:$PATH\""  > ~/.bashrc
````

Here is another example that I added Drupal Console for Drupal Commerce 2.x image https://github.com/INsReady/docker-drupal-commerce/blob/master/8/Dockerfile

**Comment by iBobik** [comment]
Thanks, I managed it already.

Jan Pobořil
http://honza.poboril.cz/

23. 10. 2015 v 6:46, Jingsheng Wang <notifications@github.com>:
