### ISSUE TITLE
Error The website encountered an unexpected error. Please try again later. Drupal 8.7.10

### ISSUE THREAD

**Issue by johnsi15** [docker-library/drupal#161]
Finishing the installation gives me this error, is connected to mariadb: 10.4.

This is the command you executed.
`docker run --name op8 -p 80:80 -d --net=drupalnet drupal:8.7.10`

With the latest version it works correctly _**drupal:latest**_

Drupal\Core\Config\UnmetDependenciesException: Configuration objects provided by <em class="placeholder">standard</em> have unmet dependencies: <em class="placeholder">core.entity_form_display.node.article.default (image.style.thumbnail, image, path), core.entity_form_display.node.page.default (path), core.entity_form_display.user.user.default (image.style.thumbnail, image), core.entity_view_display.node.article.default (image.style.large, image), core.entity_view_display.node.article.teaser (image.style.medium, image), field.field.node.article.field_image (image), field.storage.node.field_tags (taxonomy)</em> in Drupal\Core\Config\UnmetDependenciesException::create() (line 98 of core/lib/Drupal/Core/Config/UnmetDependenciesException.php).
Drupal\Core\Config\UnmetDependenciesException::create('standard', Array) (Line: 481)
Drupal\Core\Config\ConfigInstaller->checkConfigurationToInstall('module', 'standard') (Line: 132)
Drupal\Core\ProxyClass\Config\ConfigInstaller->checkConfigurationToInstall('module', 'standard') (Line: 158)
Drupal\Core\Extension\ModuleInstaller->install(Array, ) (Line: 83)
Drupal\Core\ProxyClass\Extension\ModuleInstaller->install(Array, ) (Line: 1659)
install_install_profile(Array) (Line: 702)
install_run_task(Array, Array) (Line: 577)
install_run_tasks(Array, NULL) (Line: 118)
install_drupal(Object) (Line: 44)

**Comment by wglambert** [comment]
There's a number of upstream issues of this going back quite a few years. And from what I can tell there's a multitude of potential causes. I would also think it could be intermittent since drupal 8.7.10 and `latest` are the same

https://www.drupal.org/project/drupal/issues/2594351
https://www.drupal.org/forum/support/installing-drupal/2017-07-25/error-during-installing-drupal-835
https://www.drupal.org/project/drupal/issues/2558371

**Comment by wglambert** [comment]
Were you able to resolve this issue?

**Comment by johnsi15** [comment]
no but thanks for answering. I ended up doing something else.

**Comment by yosifkit** [comment]
Closing old issue.

(also note that Drupal 8 is end of life)
