### ISSUE TITLE
7.68/7.69 Security Update

### ISSUE THREAD

**Issue by vinyfc93** [docker-library/drupal#164]
Hello,

Drupal has just released version 7.69 that fixes security issues.

The release of tags 7.69 would be most welcome.

Thank you

**Comment by tianon** [comment]
See https://doi-janky.infosiftr.net/job/update.sh/job/drupal/4757/console
-- a version bump is in-progress.

**Comment by yosifkit** [comment]
And done: https://github.com/docker-library/drupal/commit/045b0f25b96b1fe0e660b736d28ef385253a32e7.

https://github.com/docker-library/drupal#see-a-change-merged-here-that-doesnt-show-up-on-docker-hub-yet
