### ISSUE TITLE
Support Drupal 9 release

### ISSUE THREAD

**Issue by skyred** [docker-library/drupal#169]
drupal 9.0.0-alpha1 was already released, see https://www.drupal.org/project/drupal/releases/9.0.0-alpha1

Below is a list of things we need to do

- [ ] Use PHP 7.4, as[ Drupal 9 now requires at least PHP 7.3 to be installed](https://www.drupal.org/node/3089166). [PHP 7.4 is also supported](https://www.drupal.org/project/drupal/issues/3086374)

- [ ] Add Composer as part of the install, as [For sites created on Drupal 8.8.0 or later, Even if you installed Drupal 8.8.0 from the tarball, Composer was pre-installed.](https://www.drupal.org/docs/8/install/add-composer-to-an-existing-site#s-for-sites-created-on-drupal-880-or-later)

- [ ] Use the new recommended file structure layout, as [This layout is recommended because it allows you to configure your webserver to only provide access to files inside the "web" directory. Keeping the vendor directory outside of the web server's document root is better for security. ](https://www.drupal.org/docs/develop/using-composer/starting-a-site-using-drupal-composer-project-templates#s-drupalrecommended-project), and not using the [legacy layout](https://www.drupal.org/docs/develop/using-composer/starting-a-site-using-drupal-composer-project-templates#s-drupalrecommended-project)

    - [ ] Update Apache config (We can avoid this, if we do https://github.com/docker-library/drupal/issues/169#issuecomment-609384502)

    - [ ] Update WORKDIR
    
    - [ ] Update Travis CI

    - [ ] Update README

    - [ ] Probably many more

**Comment by yosifkit** [comment]
Are these steps that you are working on? I want to get started next week and don't want to duplicate any work you've already begun. 

For the first one about php 7.4, that should just be using the commented out line for `[7]` and making it for `[9]` in `update.sh`:

https://github.com/docker-library/drupal/blob/2a23b1f942e665bd6af361997c96397601d1b3ed/update.sh#L14-L17

**Comment by skyred** [comment]
@yosifkit thanks for stepping up. I haven't got approval from my company to contribute time to this yet.  So, please go ahead, and thank you!

**Comment by mstenta** [comment]
In case this is helpful to the process, here is a `Dockerfile` that we might be able to borrow some lines from: https://github.com/mstenta/docker-d8dev/blob/master/Dockerfile

It overrides the `drupal:8` image, installs composer, creates a new project from `drupal/recommended-project`, and configures the Apache webroot to point to `/var/www/html/web` (among some other things that we don't need upstream).

Just a quick thing I threw together for my own D8 module development environments - thought it worth linking here for reference. Excited to see some of these things upstream in this repo!

**Comment by yosifkit** [comment]
Started on 9.0: https://github.com/infosiftr/drupal/tree/9.0-rc

Still need to figure out how to cleanly add an extra section in the template for installing composer as well as the new layout changes.

**Comment by skyred** [comment]
How about

````
WORKDIR /var/www/
ENV DRUPAL_VERSION 9.0.0-beta1
RUN composer create-project drupal/recommended-project:{DRUPAL_VERSION} /var/www/web \
cd ./web \
chown -R www-data:www-data sites modules themes
````

**Comment by skyred** [comment]
Please be aware of an option that we can still use `html` as the folder, if we do
````
RUN composer create-project --no-install drupal/recommended-project:{DRUPAL_VERSION} /var/www \
USE_BASH_TO_REPLACE_WEB_WITH_HTML_IN composer.json \
composer install
````

**Comment by skyred** [comment]
@yosifkit Have you had a chance to think about this? Would you like me to put my suggestion above in a MR?

**Comment by tanarurkerem** [comment]
Hi, I would like to move forward this issue(9.0.0 was appeared), but I need help. I found @yosifkit repo (https://github.com/infosiftr/drupal/tree/9.0-rc) and I found an MR (https://github.com/docker-library/drupal/pull/158) with issue (https://github.com/docker-library/drupal/pull/158#pullrequestreview-306224792) What shall I do?

a) Fork a new repo from official and work on it?
b) Fork @yosifkit and @philltran repos and work on it?

**Comment by andypost** [comment]
Is there any blockers left?

**Comment by ThomasVuillaume** [comment]
Hello guys, what are the news on this one ?

Just to give you some helper links, a Drupal 9 version is already shipped here by Wodby. Did not try it for now, though : https://github.com/wodby/drupal

**Comment by yosifkit** [comment]
Sorry for the delays! :bowing_man: I was finally able to take time and get my branch updated, see #176.
