### ISSUE TITLE
Update base image to PHP 7.4

### ISSUE THREAD

**Issue by sylvainar** [docker-library/drupal#170]
Hello there,

It seems that nothing is stopping us from upgrading to PHP 7.4 according to this documentation: https://www.drupal.org/docs/8/system-requirements/php-requirements

Did anyone tried to run Drupal on 7.4 with this setup?

**Comment by yosifkit** [comment]
Fixed by #174

**Comment by marcelovani** [comment]
I have a small issue where I am using Drush 8 on a Drupal 7 site, but how that PHP is has been upgraded to 7.4, it breaks Drush
see compatibility https://www.drush.org/install/

**Comment by yosifkit** [comment]
I'm confused, both Drupal (https://www.drupal.org/project/drupal/issues/3081386) and Drush (https://github.com/drush-ops/drush/issues/4376) claim to support PHP 7.4. If there is a bug, then it likely should be filed with them.

**Comment by marcelovani** [comment]
I think you are right, after cleaning up docker it now works correctly, I also got confused because of the docs, I will ping them to have this updated
