### ISSUE TITLE
$PORT env var for http port

### ISSUE THREAD

**Issue by JasonWoof** [docker-library/drupal#173]
When I run this docker as my user (so eg uploaded files will be owned by me) I get this error:

(13)Permission denied: AH00072: make_sock: could not bind to address 0.0.0.0:80

please listen on $PORT instead of 80 if that env var is set.

**Comment by wglambert** [comment]
https://www.w3.org/Daemon/User/Installation/PrivilegedPorts.html
>The TCP/IP port numbers below 1024 are special in that normal users are not allowed to run servers on them.

https://github.com/docker-library/docs/tree/master/drupal#running-as-an-arbitrary-user
https://github.com/docker-library/docs/tree/master/php#running-as-an-arbitrary-user
>you can add `--sysctl net.ipv4.ip_unprivileged_port_start=0`
