### ISSUE TITLE
Add /opt/drupal/vendor/bin to PATH

### ISSUE THREAD

**Issue by davidbarratt** [docker-library/drupal#177]
It would be really helpful if the `/opt/drupal/vendor/bin` folder were added to the `PATH`. This would make it possible to install Drush with composer and it would be usable without additional commands or configuration. 
https://www.drush.org/install/

**Comment by yosifkit** [comment]
Seems sane to me.  What do you think @skyred?

**Comment by tianon** [comment]
I wasn't sure on `COMPOSER_BIN_DIR`, but adding `/opt/drupal/vendor/bin` to `PATH` seems :100:% reasonable/sane to me! :smile:

**Comment by skyred** [comment]
oh yeah, this is super useful!
