### ISSUE TITLE
Composer 2

### ISSUE THREAD

**Issue by mstenta** [docker-library/drupal#185]
Curious if there are plans or interest to update to Composer 2 in the D9 images?

**Comment by yosifkit** [comment]
I *think* we could, but I don't know what impact that would have on users of the image if the `composer` version in the image suddenly changed (https://www.drupal.org/docs/develop/using-composer/preparing-your-site-for-composer-2).

**Comment by skyred** [comment]
Which version of composer to use is documented in the Dockerfile. Here is the MR to fix the composer version on Drupal 9.1.x https://github.com/docker-library/drupal/pull/188

**Comment by tianon** [comment]
Fixed by #188
