### ISSUE TITLE
Offer a base image with PHP 7.

### ISSUE THREAD

**Issue by ericbarrette** [docker-library/drupal#189]
I think the move to PHP 8 was a bit premature for the 9.1.x images. Contributed modules and vendor packages are not all ready for PHP 8.

Also, see the official requirements for D9, updated on January 6th 2021.

https://www.drupal.org/docs/understanding-drupal/how-drupal-9-was-made-and-what-is-included/environment-requirements-of
> Drupal 9 requires at least PHP 7.3. PHP 7.4 is also supported but not required. PHP 8 is not yet supported, but work will be done to support PHP 8 as soon as possible.

Would it still make sense to still support a PHP 7 image?

**Comment by mstenta** [comment]
I would find this useful too. We are using Drupal 9.1, but explicitly kept the `drupal` Docker image back to `drupal:9.0` because we can't make the move to PHP 8 yet.

**Comment by piopi** [comment]
I second that, we are also using Drupal 9.1 and some of our packages are not compatible with PHP 8, it would be useful to have it.

**Comment by mstenta** [comment]
Thank you @yosifkit and @tianon! You rock!

**Comment by mstenta** [comment]
I see that there are now `9.1/php7.4` and `9.1/php8.0` subdirectories in the repo. However the corresponding images are not listed on https://hub.docker.com/_/drupal yet. Is there more to do before these become available?

**Comment by ericbarrette** [comment]
@mstenta this is the PR you have to follow https://github.com/docker-library/official-images/pull/9533

> However the corresponding images are not listed on https://hub.docker.com/_/drupal yet.

This is explained in the README.md, but essentially it's managed by another repository.
https://github.com/docker-library/drupal/blob/master/README.md#see-a-change-merged-here-that-doesnt-show-up-on-docker-hub-yet

I'm not sure about the timeline though.
