### ISSUE TITLE
Drupal 9.3 (9.1.x will no longer receive security support)

### ISSUE THREAD

**Issue by ericbarrette** [docker-library/drupal#204]
Drupal 9.3 was released on December 8th and 9.1.x will no longer receive security support.

https://www.drupal.org/project/drupal/releases/9.3.0

> Drupal 9.3.x contains new features, and should be the target for new site development. Drupal 9.2.x will continue to have security support until June 2022.
> 
> **9.1.x and 8.9.x will no longer receive security support, so sites on a Drupal 8 or 9 version earlier than 9.2.x should upgrade to a supported release as soon as possible.**

PHP 8.0.x is recommended, but PHP 7.3.x should still be supported.

**Comment by yosifkit** [comment]
Thanks for the reminder! PR opened in #205.
