### ISSUE TITLE
Automated updates are failing 

### ISSUE THREAD

**Issue by kjostling** [docker-library/drupal#207]
https://doi-janky.infosiftr.net/job/update.sh/job/drupal/

Anyone got time to fix that? Please!

**Comment by jakevis** [comment]
+1

Looks like the build server is out of disk?

`unable to prepare context: unable to 'git clone' to temporary context directory: error fetching: error: unable to create temporary file: No space left on device`

**Comment by tianon** [comment]
It turns out it was actually inodes thanks to `docker build <git-url>` sometimes leaving behind `/tmp/docker-build-git*` folders. :weary:

Thanks!
