### ISSUE TITLE
Missing webP support

### ISSUE THREAD

**Issue by marcbria** [docker-library/drupal#209]
GD is compiled without webp support.

Webp is required by some distros and by some modules.

Would be nice to offer a php with webp.

**Comment by wglambert** [comment]
You can add it right now by making a derivative Dockerfile to use. But if upstream recommends it then we'll look to incorporate it into the image

```console
$ docker build -t drupal:test - << EOF
FROM drupal
RUN apt update && apt install -y --no-install-recommends \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libwebp-dev \
        libpng-dev && \
    rm -rf /var/lib/apt/lists/*
RUN docker-php-ext-configure gd --with-freetype --with-webp --with-jpeg && \
    docker-php-ext-install gd
EOF

Sending build context to Docker daemon  2.048kB
Step 1/3 : FROM drupal
 ---> 8949ffd1143b
Step 2/3 : RUN apt update && apt install -y --no-install-recommends         libfreetype6-dev         libjpeg62-turbo-dev         libwebp-dev         libpng-dev &&     rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> 41af28f151f8
Step 3/3 : RUN docker-php-ext-configure gd --with-freetype --with-webp --with-jpeg &&     docker-php-ext-install gd
 ---> Using cache
 ---> 0af7bccdcf8d
Successfully built 0af7bccdcf8d
Successfully tagged drupal:test

$ docker run --rm drupal:test php -i | grep -i webp
WebP Support => enabled

$ docker run --rm drupal:test php -r "var_dump(gd_info());" | grep -ia1 webp
  bool(true)
  ["WebP Support"]=>
  bool(true)
```

**Comment by marcbria** [comment]
Thanks a lot for answer so fast and in a so detailed way.

I'm using your image from a docker-compose so the derivative means I will need to keep separate images. 

Is there a way to enable php extensions over your image?

I'm ok in calling an starter script every time I start the image so would be a good place to install it till is incorpored.

I tried doing an "apt update && apt-get install <php-whatever>" but the image refuses to install it.

Thanks for your help,
m.

**Comment by wglambert** [comment]
The `docker build -t drupal:test` builds a new image named `drupal:test`. So in the docker-compose.yml you would just add the `:test` tag to the name of the image.

The Dockerfile is just passed through the command line in that example
```dockerfile
FROM drupal
RUN apt update && apt install -y --no-install-recommends \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libwebp-dev \
        libpng-dev && \
    rm -rf /var/lib/apt/lists/*
RUN docker-php-ext-configure gd --with-freetype --with-webp --with-jpeg && \
    docker-php-ext-install gd
```

**Comment by marcbria** [comment]
Sorry... I didn't explain myself. 

I know how to build and tag images... but doing this I will need to build on every machine instead of pulling it from a central repository (dockerHub).

My real question was about how to enable the webp support inside a running container, but your last post (that is an extract of the former one) is crystal clear. 

Tested and is working like a charm.

Thanks a lot,
m.
