### ISSUE TITLE
Inquiry for apache compile option

### ISSUE THREAD

**Issue by sunghyun-yang** [docker-library/drupal#244]
Hello,

I am curious about the apache compile option in drupal container.

I would like to compare the apache compile option in drupal container with the apache compile option in bitnami container.

In bitnami, I can find the compile option in the config.nice file, however, I cannot find any information of apache compile option in drupal container.

May I know the compile option(e.g., ./configure --enable-so --enable-ssl) of apache which drupal supports?

**Comment by tianon** [comment]
The Apache images here get their Apache from the PHP base images, which in turn just install Debian's Apache packages, so that's where you'll need to look to find the options you're looking for.
