### ISSUE TITLE
Drupal Pod is crashing when we enable Readonly file system as True without error

### ISSUE THREAD

**Issue by vikramdevops123** [docker-library/drupal#257]
Drupal Pod is crashing when we enable Read only file system as True without error.  

As part of pen test, it has been identified to enabled the flag , but no luck pod is crashing without any error.

Drupal Deployment file : 

![image](https://github.com/docker-library/drupal/assets/33900807/ade09da3-9a23-4a46-986a-82e27b92a433)

docker file:

![image](https://github.com/docker-library/drupal/assets/33900807/a6d1dd25-6d72-4900-a3b0-649b163a7fea)

Error:

![image](https://github.com/docker-library/drupal/assets/33900807/50b4f97e-83cf-4bd1-9d73-962adafa1136)

![image](https://github.com/docker-library/drupal/assets/33900807/56a6f089-f90c-424f-81d8-0592944ec2a8)

Can you pls help us as earliest.

**Comment by tianon** [comment]
Are you running the Drupal image we maintain (https://hub.docker.com/_/drupal)?  It looks like you're running a different one in your screenshots.

Did you add appropriate volumes/mounts for the things that Drupal needs to write to disk?

**Comment by vikramdevops123** [comment]
It's same image , we have pulled from docker hub and tagged to as per project standards and pushed to ACR.

https://hub.docker.com/layers/library/drupal/latest/images/sha256-a5173fdb1a84d3aef9dc101751692e795cd4b60bee5734d5fcad7130e4052f21?context=explore

**Comment by tianon** [comment]
Closing in favor of https://github.com/docker-library/drupal/issues/258 (please don't open new issues for the same discussion)
