### ISSUE TITLE
Drupal Pod is crashing when we enable Readonly file system as True without error

### ISSUE THREAD

**Issue by vikramdevops123** [docker-library/drupal#258]
Drupal kubernates Pod is crashing when we enable Read only file system as True without error.  

As part of pen test, it has been identified to enabled the flag , but no luck pod is crashing without any error.

Drupal Deployment file : 

![image](https://github.com/docker-library/drupal/assets/33900807/ade09da3-9a23-4a46-986a-82e27b92a433)

docker file:

![image](https://github.com/docker-library/drupal/assets/33900807/a6d1dd25-6d72-4900-a3b0-649b163a7fea)

Error:

![image](https://github.com/docker-library/drupal/assets/33900807/50b4f97e-83cf-4bd1-9d73-962adafa1136)

![image](https://github.com/docker-library/drupal/assets/33900807/56a6f089-f90c-424f-81d8-0592944ec2a8)

Can you pls help us as earliest. we have added correct  mount point but still it is crashing.

mount point : 

![image](https://github.com/docker-library/drupal/assets/33900807/8c71bba0-f88d-4711-8694-f7ae569c9bff)

**Comment by mstenta** [comment]
Drupal writes to the `/tmp` directory as well, so you may need to mount that as a volume. There may be other directories as well, but it looks like you got most of the ones that come to mind.

Please report back with the final list of directories needed if you figure this out. I'm curious.

**Comment by tianon** [comment]
I'd also recommend checking the container logs -- they probably contain clues as to why it's failing to start.

**Comment by vikramdevops123** [comment]
no errors in logs :(
