### ISSUE TITLE
Cannot load the latest drupal 8

### ISSUE THREAD

**Issue by keithyau** [docker-library/drupal#26]
i use the command below try install drupal 8 latest version.

sudo docker run --name d8docker9 --link drupaldb3:mysql -p 8892:80 -d drupal:8.0.0 

but it always load drupal rc2 no matter i try drupal:8 drupal:latest drupal:8.0.0

thanks your help ~

![image](https://cloud.githubusercontent.com/assets/659311/11359106/e5d7923c-92b3-11e5-88ce-753f1bfe5807.png)

**Comment by csandanov** [comment]
Same here, but I see rc4

**Comment by skyred** [comment]
The Dockerfile looks correc https://github.com/docker-library/drupal/commit/898b3178e7d1737347fe0602726b38c4bb300330t. I think there was a build error on the docker register side. We just need to trigger the image rebuild.

**Comment by tianon** [comment]
Bizarre -- I've given the image a re-push; can someone test that it's fixed or whether we need to do further digging? :pray:

**Comment by skyred** [comment]
I tested it just now. Now, we are truly on __8.0.0__. Thanks @tianon

**Comment by tianon** [comment]
:+1: :metal:

**Comment by mstenta** [comment]
@tianon I think this can be closed.
