### ISSUE TITLE
Drupal 11 requires PHP 8.3 (remove PHP 8.2 variant)

### ISSUE THREAD

**Issue by csandanov** [docker-library/drupal#265]
Drupal 11 requires at least PHP 8.3:

https://www.drupal.org/docs/getting-started/system-requirements/overview#s-php--2

The PHP 8.2 image will be this error:
```
<b>Fatal error</b>:  Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.3.0". You are running 8.2.22. in <b>/opt/drupal/vendor/composer/platform_check.php</b> on line <b>22</b><br />
```

**Comment by tianon** [comment]
Oh nice, good catch!

Hilariously, while testing 11 on PHP 8.3 yesterday, I got the following warning in my console logs:

```html
<br />
<b>Deprecated</b>:  Unknown: assert.active INI setting is deprecated in <b>Unknown</b> on line <b>0</b><br />
```

(which I _think_ comes from https://github.com/drupal/drupal/blob/eedde8084395bee3a634501194f3c4d951bbf700/.htaccess#L30)

**Comment by tianon** [comment]
Gonna add `composer check-platform-reqs` to our build so we can catch these sooner: https://github.com/docker-library/drupal/pull/267 :eyes:
