### ISSUE TITLE
"10.3" tag is still on "10.3.7" (not "10.3.8") on docker hub

### ISSUE THREAD

**Issue by kjostling** [docker-library/drupal#273]
Where there an issue in the build? I saw it took 29 minutes to execute.

**Comment by kjostling** [comment]
Perhaps the entire build got stuck. There is a 10.3.8 & 11.0.7 tag at docker-hub but there are no layers in them.

**Comment by kjostling** [comment]
fixed now from what I can tell

**Comment by yosifkit** [comment]
Apologies, it got stuck waiting for a `composer:2` rebuild that was failing.

https://github.com/docker-library/drupal/blob/7e65333b9dc9c53edbe442e9b1fc2273595a2630/10.3/php8.3/apache-bookworm/Dockerfile#L67

**Comment by kjostling** [comment]
> Apologies, it got stuck waiting for a `composer:2` rebuild that was failing.

No problem at all. Thanks for this awesome service!
