### ISSUE TITLE
Issue with permissions 

### ISSUE THREAD

**Issue by signofkoen** [docker-library/drupal#28]
When I try to install a module a get an error that I don't have permissions for writing in the module folder.

Can you guys add change permission to the dockerfile?

**Comment by juliencarnot** [comment]
I've had quite a lot of issues with permissions (might have induced some on my own...) and resolved them with:
docker exec -ti <containername> bash then chown -R www-data:www-data <folders>

However, automatic update of modules still doesn't work, so I'll watch this issue!

**Comment by signofkoen** [comment]
@juliencarnot Yeah I already fixed it. Just mention it so it can be fixed in future updates.

**Comment by yosifkit** [comment]
Fixed by https://github.com/docker-library/drupal/pull/53
