### ISSUE TITLE
make automated builds available for quicker deployment of maintenance/security releases

### ISSUE THREAD

**Issue by juliencarnot** [docker-library/drupal#36]
Drupal 8.0.4, Drupal 7.43, and Drupal 6.38, maintenance releases which contain fixes for security vulnerabilities, have been released on February 24, 2016 at 6:36pm.

This official image repo does not seem to create automated-builds, or if it is, it hasn't picked these releases yet.

Are there any plans to streamline the image building, so that we can deploy updates quicker and fix security vulnerabilities ASAP after their disclosure?

**Comment by yosifkit** [comment]
Thanks for the notice.  I have updated the Dockerfiles in https://github.com/docker-library/drupal/commit/865f61938fe7f37359d8feeb13bb03bff8f11387 and will be making the PR to [docker-library/official-images](https://github.com/docker-library/official-images) to build the updated images shortly.

**Comment by juliencarnot** [comment]
Thanks a lot!

**Comment by juliencarnot** [comment]
[Drupal 8.1.7 is out with a highly critical fix](https://www.drupal.org/SA-CORE-2016-003) and not available on the docker hub. Are there any plans/options to make automated builds for this official docker repo?

**Comment by tianon** [comment]
Is it not pulling properly for you?  I'm looking at https://hub.docker.com/r/library/drupal/tags/ and it appears to be listed:
![image](https://cloud.githubusercontent.com/assets/161631/16996371/e73932c0-4e65-11e6-8048-09d7c5890b6e.png)
![image](https://cloud.githubusercontent.com/assets/161631/16996375/efc610f2-4e65-11e6-9781-782694bdd1a8.png)

**Comment by juliencarnot** [comment]
Yes, it has been available on the 19th at night UTC, several hours after the disclosure and release.

**Comment by juliencarnot** [comment]
Sorry for asking, but Drupal 8.1.9 was released 10 hours and 19 minutes ago (assuming release article time is UTC) and the [tags page](https://hub.docker.com/r/library/drupal/tags/) show a last update 10h ago, but only the 8.1.8 release. Is there's an automatic update process (if then, at what frequency?) that reports a rounded age and did occur just before the latest release or is running update.sh a human task?

**Comment by yosifkit** [comment]
No automatic update process as of yet, we still run `update.sh` manually (though we usually do all docker-library repos in a pass).  The drupal update was merged in with https://github.com/docker-library/official-images/pull/2131 and is available on the hub as of ~30 minutes ago.

**Comment by juliencarnot** [comment]
Thanks a lot for the answer and the update!
