### ISSUE TITLE
how to use drupal fpm container with nginx container

### ISSUE THREAD

**Issue by a93ushakov** [docker-library/drupal#39]
How to use together `nginx` and `drupal:8-fpm` container?

In my practice `nginx` and `php-fpm` containers should have common volume with servable script (drupal).

As I understand, `drupal:8-fpm` image has `drupal` sources inside container (added on build stage).

Is it possible to serve `drupal:8-fpm` through `nginx` container?

**Comment by a93ushakov** [comment]
And, why on `drupal:8-fpm` dockerfile is not  exposed `php-fpm` port?

**Comment by sidhuko** [comment]
You can add a volume to override the installed files and share between nginx. I'm still looking into configuration of nginx for this but have other issues with this set of images.

**Comment by mohamed-el-habib** [comment]
Hello, please see this [Gist](https://gist.github.com/mohamed-el-habib/fd57d8aa59b1574ee7728edf128814d3), it work for me

**Comment by a93ushakov** [comment]
thank you, @mohamed-el-habib .
