### ISSUE TITLE
Provide 'onbuild' option for auto-installing Drupal from an install profile

### ISSUE THREAD

**Issue by nhoag** [docker-library/drupal#4]
Adding onbuild would bring the official Drupal image in line with other official Docker projects such as [Rails](https://registry.hub.docker.com/_/rails/), [iojs](https://github.com/nodejs/docker-iojs), etc.

See https://github.com/nhoag/docker-drupal for a working example.

**Comment by skyred** [comment]
I was thinking about this feature today.

We can take advantage of Drush installation

````
drush dl drupal --drupal-project-rename=example
cd example
drush site-install standard --db-url='mysql://[db_user]:[db_pass]@localhost/[db_name]' --site-name=Example --account-name=admin --account-pass=[useruser_pass]
````
A more detailed documentation can be found: https://www.drupal.org/documentation/install/developers

**Comment by tianon** [comment]
I'm not sure I understand the expected use case for an onbuild variant of Drupal -- can you elaborate?  My understanding of Drupal is that it's a CMS, and that modifications on top of it would be things like installing modules/themes and custom content, so I'm not sure I comprehend what an onbuild variant would accomplish (and especially what it would accomplish in a way that's not already trivial with a custom `Dockerfile` and [automated builds](https://docs.docker.com/docker-hub/builds/)/[repository links](https://docs.docker.com/docker-hub/builds/#repository-links) (to keep it up to date when the base changes)).

**Comment by skyred** [comment]
Drupal has distributions https://www.drupal.org/documentation/build/distributions, like Linux Debian, then many other distributions like Ubuntu built on top of it.

**Comment by tianon** [comment]
Ok, that makes sense, but I'm still confused as to how an onbuild variant
would help with using one of those? Especially compared to writing a
Dockerfile to just install an explicit release version of one of those
distributions (from this image or not shouldn't make much difference,
especially when some of those already include Drupal, so including it twice
is a bit wasteful, although otherwise harmless)

**Comment by skyred** [comment]
Drupal has command line tools: Drush or DrupalConsole. A wild idea is that when a "docker run" is first called, a Drupal distribution or Profile name is passed as a ENV or parameter. Then, the command line tool will take care all the installation. Maybe, this has nothing to do with "onbuild" option. I haven't really looked into this yet.

**Comment by nhoag** [comment]
I envisioned a Drupal onbuild option more as a rapid development system. It's rare to deploy Drupal without adding modules, themes, and other code to shape a build or add functionality. With a proper onbuild, code would be modified on the host using familiar tools, and deployed into the Docker container for review.

**Comment by tianon** [comment]
I'm still not convinced this makes sense as an `ONBUILD` variant.  The way `ONBUILD` works is that we can pre-define a set of `Dockerfile` instructions which are run automatically when someone does `FROM drupal:onbuild`.  There's no way to configure, change, or influence them in any way short of them including a `COPY` which then _requires_ your local tree to have specific files in place, so the flexibility of the feature is very, very limited.  As such, I'm a very _strong_ -1 on including any kind on `onbuild` variant for this image.

That being said, I'd be open to better documentation about expanding this image for more complex use cases such as adding modules, themes, etc.

Thanks!
