### ISSUE TITLE
Make this work similar as WordPress using docker-compose

### ISSUE THREAD

**Issue by clemens-tolboom** [docker-library/drupal#56]
(!docker newbie!)

Yesterday I ran docker-compose using https://hub.docker.com/_/wordpress/ which has a way better  UX then trying https://hub.docker.com/_/drupal/

WP was a no brainer but Drupal lacks a docker compose file so I got stuck. I could have used __ SQLite__

AFAIK we need environment variables first to link the two containers together?

Is it worth the effort to create this docker-compose.yml file and if so what steps are there to take?

**Comment by mstenta** [comment]
It looks like the Docker Wordpress docs include information about how to use docker-compose - but they do not actually provide a docker-compose.yml (https://github.com/docker-library/wordpress).

Is it the docs you're talking about specifically? I agree it would be good to include an example docker-compose.yml in the docs that show up on https://hub.docker.com/_/drupal/, similar to https://hub.docker.com/_/wordpress/.

Those docs are managed in a different repo: https://github.com/docker-library/docs

So I believe this request should be moved over there?

**Comment by clemens-tolboom** [comment]
It is indeed about https://hub.docker.com/_/wordpress/ presenting

> Example docker-compose.yml for wordpress:

**Comment by lupa18** [comment]
Now in docker hub comments you have an example: https://hub.docker.com/_/drupal/

**Comment by clemens-tolboom** [comment]
Thanks for the comment with example. I'll check later.

I rather have it in documentation as comment move to bottom :-/

**Comment by clemens-tolboom** [comment]
Thanks!
