### ISSUE TITLE
Ldap Connection

### ISSUE THREAD

**Issue by lopezoliveraeddy** [docker-library/drupal#59]
I've noticed that this dockerfile has no a php ldap extension, is any future version bunded with php ldap extension?

**Comment by tianon** [comment]
It looks like LDAP is an optional extension, not part of Drupal core (https://www.drupal.org/project/ldap), so I don't think it'd be appropriate for us to add this module by default unless it's used reasonably universally by the majority of Drupal users (which I cannot imagine being true, given how irritating maintaining an LDAP server is).

**Comment by yosifkit** [comment]
It should be fairly simple to add support in your own Dockerfile.  I think it should be fairly similar to the changes in https://github.com/docker-library/owncloud/pull/74.

```
FROM drupal:7
RUN apt-get update && apt-get install -y libldap2-dev && rm -rf /var/lib/apt/lists/*
RUN docker-php-ext-configure ldap --with-libdir=lib/x86_64-linux-gnu/ \
	&& docker-php-ext-install ldap
```
