### ISSUE TITLE
docker version 1.11.2

### ISSUE THREAD

**Issue by Ajeeshb** [docker-library/drupal#68]
Can I run this docker image in my Docker version 1.11.2, build b9f10c9 ?

**Comment by tianon** [comment]
@Ajeeshb it should work fine on 1.11.2, yes -- was there something that made you think it might not work?  Did you try it and run into some kind of issue/error?

**Comment by Ajeeshb** [comment]
@tianon It worked fine and the only change I found that the php version upgraded to 7.0.13 from 5.6.

**Comment by yosifkit** [comment]
The switch to php 7 was done in https://github.com/docker-library/drupal/pull/51.
