### ISSUE TITLE
Drupal 8 sqlite3 feature add

### ISSUE THREAD

**Issue by uqcgreen** [docker-library/drupal#69]
Hi there,

I pulled the Drupal 8, installed via sqlite.  When I come to install drush and do some things in it, got very stuck because the sqlite3 library wasn't installed.  Commands like drush dl and drush status would work, but nothing which touched the database.

Eventually ran drush with debug mode and realised it needed the sqlite3 library.

Might be something to add along with pdo_mysql and pdo_postgresql in the install to smooth the path for users.

Regards,

Cameron

**Comment by skyred** [comment]
This student emailed me and said: "I'm pretty sure that sqlite was already installed on the docker image that I downloaded"

https://medium.com/gci-blog-2016-lecafard/installing-drupal-using-docker-on-archlinux-sqlite-a3761cee03df#.m2mhcbl9o

What is the exact error message you received?

**Comment by tianon** [comment]
It sounds like you've installed `drush` on top of this Drupal image, is that correct?  I'm not sure how I feel about adding additional bits to the image specifically to support third-party tooling interacting with it. :confused:

I think installing the dependencies of Drush would be part of adding Drush to the image (`docker-php-ext-install` should be reasonably easy to get `sqlite3` support included).

**Comment by djcf** [comment]
Well, drush is a pretty essential tool. It's the best way to interact programatically with the drupal site, including running operations like drupal cron, which is a system requirement for drupal sites. You could rebase the build toolchain to install drupal using drush -- which I believe is now the recommended way to install drupal as well as the most supported. And having an image where d8 sites can talk to sqlite out of the box but drush/cli can't is just plain confusing.

+1 for adding drush and sqlite to the base image.

**Comment by AgoraSecurity** [comment]
Has there been any progress on this? I'm trying to setup a container with a basic installation. I want to be able to run the container and have a running site.

**Comment by tianon** [comment]
I imagine that now that we use/include `composer`, installing Drush is simpler -- can anyone confirm?
(Is this even still relevant? :see_no_evil:)

**Comment by mstenta** [comment]
We install Drush via Composer in our farmOS image: https://github.com/farmOS/farmOS/blob/eb6f1043da00b7b21d122d3cba626c4d026371c3/composer.json#L46

Never had any trouble with SQLite3 - and we run automated tests against all three database types (PostgreSQL, MySQL/MariaDB, and SQLite3).

I think this issue can be closed.
