### ISSUE TITLE
Create Drupal image with preinstalled theme

### ISSUE THREAD

**Issue by tzfrs** [docker-library/drupal#70]
In my docker-compose I have a mysql image and this drupal image. I started it and installed a new theme. However, when I remove the drupal image and create a new one the themes are gone. They're still in the database though, because I don't delete it.

Is there a possibility to create an image with a preloaded theme? What I managed to do was to create the image with preconfigured settings. I set up my Drupal site, then copied the `settings.php` to my host and in the `Dockerfile` this file is added back again to the container. This skips the installation progress, however, the site doesn't work correctly because of the themes.

And when I copy all the contents of `default/files` as well I get at least a bit of a theme, but there are still many css/js missing. So, is there a way to create the image, with a preloaded theme, throw it away, create a new one and still have the theme?

**Comment by tianon** [comment]
I think https://github.com/docker-library/drupal/issues/3 is probably relevant here (and https://github.com/docker-library/docs/pull/811, which I've just filed).

For pre-loading an image with themes though, I think it _should_ be as simple as copying them into the `themes` folder (`/var/www/html/themes`), but I have not tested/verified that.  There might be a better/cleaner way to do that as well.

**Comment by wglambert** [comment]
Question seems resolved, going to prune the issue.

See also https://github.com/docker-library/docs/tree/master/drupal#volumes
