### ISSUE TITLE
PHP version

### ISSUE THREAD

**Issue by iBobik** [docker-library/drupal#8]
Currently image use php:5.5-apache.

Drupal 7 have no problem with php:5.6, so why not use it?

**Comment by yosifkit** [comment]
Sounds reasonable, given: "it is recommended to use 5.6.5 or higher" ([drupal](https://www.drupal.org/requirements/php#8)). Using it for drupal 7 and 8 seems reasonable to me. Want to make a PR?

**Comment by tianon** [comment]
Our current choices came from
https://www.drupal.org/requirements/php#drupalversions
