### ISSUE TITLE
Add tags for php5 containers.

### ISSUE THREAD

**Issue by jonpugh** [docker-library/drupal#95]
As mentioned in https://github.com/docker-library/drupal/commit/41970d6f598cf64fe90aa63651ba52cdc384c002 many Drupal contrib modules and custom code will not work in PHP 7.  

Drupal 7 actually supports PHP 5.3 - 5.7 as well as 7.0.

It would be nice to get an official tag for Drupal on php5, especially since we have working Dockerfile at https://github.com/docker-library/drupal/blob/bee08efba505b740a14d68254d6e51af7ab2f3ea/7/Dockerfile

**Comment by tianon** [comment]
@skyred do you have any thoughts on this?

It might be useful to try and gather a few examples of third party modules that don't work with PHP 7.

**Comment by skyred** [comment]
> (**) Because PHP 7 is the newest release, extra care should still be taken with it. See the Drupal 7.50 release notes and the PHP 7 discussion for more details. However anecdotal evidence from a variety of users suggests that Drupal 7 can be successfully used on PHP 7, both before and after the 7.50 release.

Above message is from https://www.drupal.org/docs/7/system-requirements/drupal-7-php-requirements

As right now, I don't know any popular Drupal modules/themes that cannot run on PHP 7.

**Comment by skyred** [comment]
It is safe to close this issue, as PHP 5.* all reached EOL https://www.php.net/supported-versions.php
